licenses(['notice'])

cc_library(
    name = 'readline',
    textual_hdrs = [
        'emacs_keymap.c',
        'vi_keymap.c',
    ],
    srcs = [
        'bind.c',
        'callback.c',
        'colors.c',
        'compat.c',
        'complete.c',
        'display.c',
        'funmap.c',
        'histexpand.c',
        'histfile.c',
        'history.c',
        'histsearch.c',
        'input.c',
        'isearch.c',
        'keymaps.c',
        'kill.c',
        'macro.c',
        'mbutil.c',
        'misc.c',
        'nls.c',
        'parens.c',
        'parse-colors.c',
        'readline.c',
        'rltty.c',
        'search.c',
        'shell.c',
        'signals.c',
        'terminal.c',
        'text.c',
        'tilde.c',
        'undo.c',
        'util.c',
        'vi_mode.c',
        'xfree.c',
        'xmalloc.c',
    ] + [
        'ansi_stdlib.h',
        'chardefs.h',
        'colors.h',
        'config.h',
        'histlib.h',
        'history.h',
        'keymaps.h',
        'parse-colors.h',
        'posixdir.h',
        'posixjmp.h',
        'posixselect.h',
        'posixstat.h',
        'rlconf.h',
        'rldefs.h',
        'rlmbutil.h',
        'rlprivate.h',
        'rlshell.h',
        'rlstdc.h',
        'rltty.h',
        'rltypedefs.h',
        'rlwinsize.h',
        'tcap.h',
        'tilde.h',
        'xmalloc.h',
    ],
    hdrs = [
        'readline.h',
        'history.h',
    ],
    defines = [
        'READLINE_LIBRARY',
    ],
    copts = [
        '-DHAVE_CONFIG_H',
        '-DRL_LIBRARY_VERSION=\'"7.0"\'',
    ] + [
        # Suppress compile warnings.
        '-Wno-macro-redefined',
        '-Wno-parentheses',
        '-Wno-sometimes-uninitialized',
        '-Wno-unused-function',
        '-Wno-unused-label',
        '-Wno-unused-variable',
    ],
)
